export const DEFAULT_PORT = 3100;
export const DEFAULT_HOST_LOOPBACK = "127.0.0.1";

export const HEARTBEAT_MIN_INTERVAL_SEC = 30;
export const HEARTBEAT_DEFAULT_MAX_CONCURRENT_RUNS = 20;
export const HEARTBEAT_MAX_CONCURRENT_RUNS_CAP = 50;
